### ISSUE TITLE
Long filenames cause OSError

### ISSUE THREAD

**Issue by ImSoErgodic** [QUVA-Lab/artemis#113]
I'm bumping into an `OSError: [Errno 36] File name too long` when setting up experiments with many parameters. As far as I understand, I'm hitting a filesystem- and OS-dependent limit on the number of bytes that a file name and a file path can have (in my instance, 255 and 4096, respectively). I've had a look around and am not sure these can be changed without tinkering with the OS, which at the moment is not an option.

Within artemis, the issue is that many parameters, or parameters with long names or long values (e.g. lists) will easily generate directory names close to, or themselves exceeding, the limit of 255 bytes. 

The most immediate workaround I can think of is on the user's side and it's shortening parameter names, but it hinders readability and doesn't really solve the issue. Furthermore, when objects with large string representations are passed as parameters, such as a list, these can easily consume a lot of the available bytes. 

Another option I see is splitting the various components that at the moment make up the name of the experiment folder and make them a directory tree. Incidentally, the tree structure could be passed onto the experiments too, but I can understand that'd be messy: timestamp information would lose priority and would have to be stuck at the bottom of the tree and things would become problematic if one added or removed parameters to an experiment at a later stage (not an unrealistic scenario). So maybe just finding a replacing a directory with a tree would be safest and fastest.

However, there are also limits on the length of the whole path of a file, so even the latter approach would only be swiping the dust under the carpet. What may possibly solve the problem, but it would actually add some more complexity to how artemis works, is having something of a bookkeeping layer (e.g. a sqlite database, YAML files or something like that) that knows which folder contains which experiment, and that can be queried through artemis's API. In this way filenames can be short, non human-readable hashes that stay within the limits.

This being said, there may well be a trivial one-liner that solves or circumvents this problem which I'm completely unaware of, in which case I'd be eternally grateful to whomever could point that out to me.

Thanks!

**Comment by petered** [comment]
Hi.  Easy solution: 

When you create a variant, you can give it a name:

e.g. Instead of 
```
my_exp_func.add_variant(param1=1, param2=2, param3=3)
```
do:
```
ex.add_variant('my_var', param1=1, param2=2, param3=3)
```
Your experiment name will then be `my_exp_func.my_var` instead of `my_exp_func.param1=1,param2=2,param3=3`

**Comment by ImSoErgodic** [comment]
Absolutely marvellous. And without jumping through loops and holes! Thanks!!
