### ISSUE TITLE
jupyter tutorial python 3.x errors

### ISSUE THREAD

**Issue by jlhsage** [QUVA-Lab/artemis#126]
The file 'experiment_tutorial.ipynb' uses 'xrange' instead of 'range', so it throws an error on Jupyter notebooks running 3.5/6.  Also, none of the 'print' statements wrap the formatted string in parenthesis, so they all give an error with python 3.x.

**Comment by petered** [comment]
Also addressed in https://github.com/QUVA-Lab/artemis/pull/128 .  Thanks again

**Comment by jlhsage** [comment]
Hi Peter,

I've been using Artemis more and some of my colleagues have made a
request.  We would like to have our .artemis saved files on a server that
several people can access.  That way, other people can 'browse' and review
past experiments.  I see in the config files that it is possible to point
the .artemis directory to someplace other than the default home dir, but is
there a way to have the .artemis file on a server, accessed via web browser
perhaps?

If that feature is not already implemented, if you could suggest how a
newbie like me might modify Artemis to add it, our group would like that
quite a bit.  Thanks for this product, and for any advice you might give.

John

**Comment by petered** [comment]
Hi.  So while this doesn't quite exist yet, current options are:

- Put the home directory on a shared file system.
- Use the "pull" command in the browse UI to pull experiment records from other machines.
- Try using [Sacred](https://github.com/IDSIA/sacred), which used mongodb and has a web-interface.

**Comment by jlhsage** [comment]
Hi Peter,

I hope you can advise me on one small issue.  After I have run my
experiments in a Jupyter notebook the 'name.browse()' / 'show all' method
works great, but once I close the notebook, I can't figure out how to
browse those experiments again.  Is there some way to give an artemis
method the name of the last experiment and have it load the experiment and
allow browsing?

Otherwise I have to go to the '.artemis' directory and read the files raw.
I couldn't find an example of how to browse after closing the notebook, so
I would appreciate if you could tell me a way.

Thanks,

John
