### ISSUE TITLE
Access an experiment's folder path within the experiment

### ISSUE THREAD

**Issue by matthiasreisser** [QUVA-Lab/artemis#25]
Many ML libraries allow for saving checkpoints of training, or saving diagnostics that come from the library. Eg I would want to store TensorBoard Plots and my Model Checkpoints. 

What I would require is only the path in which all of artemis-related things (console output, plots, results, etc) are (going to be) stored. 

This path I can then forward to the necessary calls

**Comment by petered** [comment]
See `test_accessing_experiment_dir` in pull request: https://github.com/QUVA-Lab/artemis/pull/29

**Comment by petered** [comment]
```
======================================================================= 81 passed, 3 skipped in 144.41 seconds ========================================================================
```
