### ISSUE TITLE
Extend Experiment Tree Structure to Grid Structure

### ISSUE THREAD

**Issue by matthiasreisser** [QUVA-Lab/artemis#26]
Would allow for the further to Bayesian Hyperparameter Optimization using eg. Spearmint

**Comment by petered** [comment]
This new pull request kind of does it.  See test_variants function in test_experiment_record.  Pull: https://github.com/QUVA-Lab/artemis/pull/30

**Comment by matthiasreisser** [comment]
Thx :)
