### ISSUE TITLE
Way to run multiples of identical experiment with different seeds

### ISSUE THREAD

**Issue by matthiasreisser** [QUVA-Lab/artemis#27]
That would be convenient :)

**Comment by petered** [comment]
Probably the best is just a convenient way to create an array of variants with different seeds.  Don't see why random seed should be treated differently from other args.

**Comment by petered** [comment]
That'll be for the next pull.

**Comment by petered** [comment]
Yep, see https://github.com/QUVA-Lab/artemis/pull/30

**Comment by petered** [comment]
See test_variants function in test_experiment_record
