### ISSUE TITLE
Pass Dicts as experiment parameters

### ISSUE THREAD

**Issue by matthiasreisser** [QUVA-Lab/artemis#42]
When passing dicts, they are not correctly displayed upon changes of elements of this dictionary.
Ideally the dictionary would be parsed and only the corresponding changed entry displayed to the user. Eg if `my_dict["bla"]` changed from `"a"` to `"b"`, one would see:
`my_dict.bla:a -> my_dict.bla.b`

**I am a pretty little princess, look at me.  LALALALA**

**Comment by petered** [comment]
Hi Pretty Princess, 

the function that implements this is [ExperimentRecord.get_invalid_arg_note](https://github.com/QUVA-Lab/artemis/blob/master/artemis/experiments/experiment_record.py#L426)

If I were to implement this I might go for some kind of stand-along function that calls itself recursively and appends the list of changed args (and subargs) to a string.

**Comment by matthiasreisser** [comment]
Hey handsome prince, what do you say, does commit d9072e19bc7b859a308c50f0168aead6cf9b6bb9 solve this problem?

**Comment by matthiasreisser** [comment]
Hey @petered, something wonky with current master implementation of get_record_invalid_arg_string. When not changing the arguments to the experiment at all, I get this:
```No: Args changed!: {model_config['scale']:1.0,model_config['prior_var']:1.0,training_config['precision']:Already Seen object at 0x105650060,optimizer_config['decay_rate']:1.0,data_config['beta']:0.333333333333}->{model_config['scale']:Already Seen object at 0x7faad9d0dc78,model_config['prior_var']:Already Seen object at 0x7faad9d0dc78,training_config['precision']:Already Seen object at 0x10458ffc0,optimizer_config['decay_rate']:Already Seen object at 0x7faad9d0dc78,data_config['beta']:Already Seen object at 0x7faad9d0dbd0}```

What's with all the "Already Seen object at" thingys?

**Comment by petered** [comment]
Addressed in https://github.com/QUVA-Lab/artemis/pull/68

**Comment by petered** [comment]
can't reproduce your latest error.

**Comment by petered** [comment]
GIMMA A FAILING TEST PRINCESS

**Comment by matthiasreisser** [comment]
This test fails:
```
def test_invalid_arg_detection_2():
    """
    Check that we notice when an experiment is redefined with new args.
    """

    with experiment_testing_context(new_experiment_lib=True):

        a = {"a%s"%i for i in range(10000)}
        @experiment_function
        def my_experiment_gfdsbhtds(a=a):
            # a["a"] = [2]
            return None

        rec = my_experiment_gfdsbhtds.run()

        assert rec.is_valid()
        clear_all_experiments()

        @experiment_function
        def my_experiment_gfdsbhtds(a=a):
            return None

        assert rec.is_valid()  # Assert that the args still match
```

**Comment by matthiasreisser** [comment]
passes, thx
