### ISSUE TITLE
Using Matplotlib inside experiment framework

### ISSUE THREAD

**Issue by matthiasreisser** [QUVA-Lab/artemis#44]
Importing matplotlib has unexpected behaviour when it has been imported before within the artemis framework. 
Usecase:
Writing own display_function inside the experiment framework.
When importing matplotlib.pyplot within own_display_function(), plots don't show upon calling plt.show()

On the other hand, when importing matplotlib.pyplot before calling artemis, artemis throws the following warning:
```
/Users/matthias/virtualenvs/tensorflow8/lib/python2.7/site-packages/matplotlib/__init__.py:1401: UserWarning:  This call to matplotlib.use() has no effect
because the backend has already been chosen;
matplotlib.use() must be called *before* pylab, matplotlib.pyplot,
or matplotlib.backends is imported for the first time.
```

What is the intended form of use?

Thx :)

**Comment by petered** [comment]
Is this still an issue?

**Comment by matthiasreisser** [comment]
I can't remember it, so I guess no...
