### ISSUE TITLE
Create .artemisrc during setup; Update README

### ISSUE THREAD

**Issue by matthiasreisser** [QUVA-Lab/artemis#5]
artemisrc should really be created during installation, not at first import

**Comment by petered** [comment]
It's a good safety in case it gets deleted.  Checking whether the directory exists takes like a millisecond.

**Comment by matthiasreisser** [comment]
Agree. But should it not nevertheless be created during installation?
Is it enough to copy & adapt the code into the setup.py?

**Comment by petered** [comment]
Probably.
