### ISSUE TITLE
Feature Request: History of inputs

### ISSUE THREAD

**Issue by matthiasreisser** [QUVA-Lab/artemis#58]
Simple Version: Display the last input to the ui
Elaborate Version: Replicate Terminal arrow-key functionality

**Comment by petered** [comment]
This supposedly [can be solved easily](https://stackoverflow.com/questions/15416054/command-line-in-python-with-history), but when I tried it it didn't work

**Comment by matthiasreisser** [comment]
I see - do you have code with your attempt?

**Comment by petered** [comment]
ah, I see, it works, but just not in pycharm.

    
    import readline
    
    while True:
    
        print raw_input('prompt >> ')

**Comment by petered** [comment]
Do you ever run experiments from command line?

**Comment by matthiasreisser** [comment]
This works fine now outside Pycharm. I guess that's enough! Thx
