### ISSUE TITLE
bad local importing 

### ISSUE THREAD

**Issue by ncullen93** [QUVA-Lab/artemis#83]
Get this error trying to run `from artemis.experiments import experiment_function`

```
/Users/.../anaconda/lib/python3.6/site-packages/artemis/experiments/__init__.py in <module>()
----> 1 from decorators import experiment_function, experiment_root, ExperimentFunction
      2 from experiments import capture_created_experiments, load_experiment
      3 from experiment_record import load_experiment_record

ModuleNotFoundError: No module named 'decorators'
```

Probably need something like `from .decorators import ...` Is this project only python 2.7? Maybe need a `from __future__ import absolute_import` in there as well? Nothing really works for me using python3.6

There's also a ton of full path imports in the code.. will cause a ton of issues. nice project though :)

**Comment by petered** [comment]
Thanks.  I've addressed that here: https://github.com/QUVA-Lab/artemis/pull/84 .  Yeah, we only developed for python 2.7 (I'll make a note on the reddit).  We should really extend support to Python 3.

**Comment by petered** [comment]
@ncullen93 We finally have a proper release with python 3, so I finally get to close this issue.
