### ISSUE TITLE
Feature Request: Support for python 3

### ISSUE THREAD

**Issue by matthiasreisser** [QUVA-Lab/artemis#85]

**Comment by alain2208** [comment]
+1

**Comment by cclauss** [comment]
Step one is https://github.com/cclauss/artemis/blob/patch-3/docs/Python3_printing.md

**Comment by cclauss** [comment]
- [ ] Undefined names #86
- [ ] Import MovingImagePlot, TextPlot, plt #88 or Remove Bokeh Backend #90 
- [ ] Ran 2-to-3 #93 
- [ ] Python 3 functions and lambdas cannot take explicit tuple param #96

**Comment by petered** [comment]
[fancy checkbox] Get unittesting running for python 2 and 3

**Comment by cclauss** [comment]
;-) Added above...

`- [ ] fancy checkbox`

**Comment by cclauss** [comment]
https://docs.python.org/3/howto/pyporting.html

Do we want to do compatibility fixes as needed in each file* or use a compatibility library like [six](https://pythonhosted.org/six) or [futurize](http://python-future.org/automatic_conversion.html) or [modernize](https://python-modernize.readthedocs.io)?

`*`compatibility fixes as needed in each file might look like this:
```python
try:
    xrange          # Python 2
except NameError:
    xrange = range  # Python 3
```

**Comment by petered** [comment]
Alright.  So it seems we have a working artemis for python 3 - great!  And much thanks @cclauss  for getting involved in this.  I'm going to merge in a few more changes this week, and then will release an Artemis 2.0.0

**Comment by petered** [comment]
I'll close this once we have a release supporting Python 3 up on Pypi

**Comment by petered** [comment]
Well, that took some time, but the Python3 version is now up on PyPi
