### ISSUE TITLE
Undefined names

### ISSUE THREAD

**Issue by cclauss** [QUVA-Lab/artemis#86]
Undefined names can raise NameErrors at runtime.

These three issues need to be fixed:
* https://travis-ci.org/QUVA-Lab/artemis/jobs/272010525#L540-L549

**Comment by cclauss** [comment]
Updated comments above.

**Comment by petered** [comment]
Created https://github.com/QUVA-Lab/artemis/pull/101 to address this

**Comment by petered** [comment]
I believe this is resolved now.  Will close unless I've missed something.
