### ISSUE TITLE
Remove Bokeh Backend

### ISSUE THREAD

**Issue by petered** [QUVA-Lab/artemis#90]
It needs to die.

The remote-plotting has done away with the need for it for now.  The backend complicates imports, because you often end up importing things from that backend instead of the matplotlib one by mistake.

**Comment by matthiasreisser** [comment]
Eulogy is planned for 10am tomorrow

**Comment by cclauss** [comment]
Was this closed with #97 ?

**Comment by petered** [comment]
Yep
